---
- name: Install docker on all app nodes
  hosts: web
  become: true
  roles:
    - docker

- name: Pull Docker from Docker Hub and Run on the EC2
  hosts: web
  tasks:
    - name: Pull Docker image from DockerHub
      docker_image:
        name: mredaammer/practice:latest
        source: pull
        state: present

    - name: Run the  container From pulled image
      docker_container:
        name: app
        image: mredaammer/practice:latest
        state: started
        ports:
          - "80:8080"

