name: PyTest

on: 
    push:
        branches:
            - main
        paths:
            - '**/*.py' 
            - 'templates/**'
            - 'requirements.txt'
            - '.github/workflows/actionspy.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run: |
          
          pip install -r requirements.txt
          pip install pytest
          pip install webdriver-manager
    
      - name: Start Application Server
        run: |
           docker build -t practice .
           docker run --rm -d -p 5000:8080 practice
           sleep 10
      - name: Verify Chromedriver Path
        run: which chromedriver
    
      - name: Running tests
        run: |
          pytest
  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    if: success()    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: mredaammer
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: docker build -t mredaammer/practice .
           
      - name: Tag With Git Hub Commit
        if: startsWith(github.ref, 'refs/tags/')
        run: docker tag mredaammer/practice:latest mredaammer/practice:${GITHUB_REF#refs/tags/}
      
      - name: Build and  image with tag
        run: docker push mredaammer/practice --all-tags  